export const authorizationToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWmFjaGFyeWFoIiwic3R1ZGVudElEIjoiMjE4OTU0MiIsImlhdCI6MTY3MDI1NjQzNywiZXhwIjoxNjcyODQ4NDM3fQ.9fvW1XBPa7SA7Y2ec6dmxIEEMGp08xGlCSaVBF_tc0k";

export const top10route = "https://quiz-leaderboard-58cf6.nn.r.appspot.com/scores/top10";